services:
  - type: web
    name: polymarket-automator-bot
    env: python
    buildCommand: ""
    startCommand: python3 main.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
